### PR TITLE
Add job information to statuses

### PR DESCRIPTION
**Pull request by ghaydarov**
This PR adds job information to the status hash. `job.status` still returns the status only. 

I added job information so that we can get more information about the job. We currently have no way of getting job information from ActiveJob. I think this will be fine spot to do that.

This is especially helpful when one wants to have some kind of interface in their app about the job statuses, because we can only get `[:queued, :working, :completed, :failed]` with job ID. It would be helpful if we can give more information of what was the job name, failure message if it's failed etc.

Please let me know if you have any suggestions as to where it should go, or any implementation details.

### CODE REVIEW

**Comment by ghaydarov** [comment]
@inkstak Could not add you as a reviewer. So pinging you here.

**Comment by inkstak** [comment]
Thanks for the suggestion.
I am concerned about the size of `job.serialize` and its factor on increasing the cache size, especially when queuing thousands of jobs. ActiveJob isn't really frugal when it comes to serializing non-JSON data (GlobalId, symbols..)

Right now, It should be possible to add this feature on your own project..

```ruby
class ApplicationJob < ActiveJob::Base
  before_enqueue do |job|
    job.status[:job] = job.serialize
  end
end
```

..but I understand the idea to get it out of the box.
I'll make few tests on my side and I'll come back to you.

**Comment by ghaydarov** [comment]
> Thanks for the suggestion. I am concerned about the size of `job.serialize` and its factor on increasing the cache size, especially when queuing thousands of jobs. ActiveJob isn't really frugal when it comes to serializing non-JSON data (GlobalId, symbols..)
> 
> Right now, It should be possible to add this feature on your own project..
> 
> ```ruby
> class ApplicationJob < ActiveJob::Base
>   before_enqueue do |job|
>     job.status[:job] = job.serialize
>   end
> end
> ```
> 
> ..but I understand the idea to get it out of the box. I'll make few tests on my side and I'll come back to you.

Thank you @inkstak.

That's a valid concern. Please let me know how your tests go. 
We have bigger application with many engines and adding them each time would be a bit hassle and implementation detail that would need explanation all the time. Thank you for your time.

**Comment by inkstak** [comment]
So, I would definitively not add serialized jobs to the cache store by default, especially after enqueing jobs.
In our application, we may need to triple our cache plan to prevent memory issues when we enqueue millions of jobs.

An alternative could be to globally configure the stored data.

```ruby
# config/initializers/activejob_status.rb

# Define what data you want to store.
# Available options are: :status, :serialized_job, :exception
# Default is [:status]
#
ActiveJob::Status.options = { includes: %i[status serialized_job exception] }
```

One last point: cache is volatile. Between enqueuing and performing, cached data may expire and be lost.
The status must be updated at every hook:

```ruby
class ApplicationJob < ActiveJob::Base
  if ActiveJob::Status.options.fetch(:includes, []).include?(:serialized_job)
    before_enqueue { |job| job.status[:job] = job.serialize  }
    before_perform { |job| job.status[:job] = job.serialize  }
  end
end
```

**Comment by ghaydarov** [comment]
> So, I would definitively not add serialized jobs to the cache store by default, especially after enqueing jobs. In our application, we may need to triple our cache plan to prevent memory issues when we enqueue millions of jobs.
> 
> An alternative could be to globally configure the stored data.

I like the idea of making them optional. 

I pushed a new commit c4783a6d1367f1af12851e47d117e460d358614d related to that. Please let me know if that needs any improvements or a fix.

**Comment by ghaydarov** [comment]
Thanks for merging this @inkstak. Great work. When you get a chance, can you please release it?

**Comment by inkstak** [comment]
Thanks for your contribution. It's released.

**Pull request merged**
